### ISSUE TITLE
Empty results

### ISSUE THREAD

**Issue by olafveerman** [WorldBank-Transport/rra-frontend#111]
ETA's of < 60 seconds will show empty on the results page:

![image](https://cloud.githubusercontent.com/assets/751330/26311198/6bae795a-3ed1-11e7-9907-2c01e3e4ab33.png)

Introduced by: https://github.com/WorldBank-Transport/rra-frontend/commit/ad37f0b23353aad3cb26c4992ac9d41d66dad9aa

**Comment by danielfdsilva** [comment]
This now displays as `<1M`
