### ISSUE TITLE
Design UI components

### ISSUE THREAD

**Issue by olafveerman** [WorldBank-Transport/rra-frontend#3]

**Comment by ricardomestre** [comment]
Sharing the design direction. Note that the final design implementation may differ a little bit.

![projects-hub 2x](https://cloud.githubusercontent.com/assets/1016701/23311629/a7f15cc8-faae-11e6-9d85-dfcfa58886de.png)
---
![projects-single-draft 2x](https://cloud.githubusercontent.com/assets/1016701/23311628/a7e77384-faae-11e6-8274-ee822d4266d8.png)
---
![scenarios-create-dialog 2x](https://cloud.githubusercontent.com/assets/1016701/23311627/a7d0dcf0-faae-11e6-914a-e0d8bb4c77c7.png)
---
CC / @Holly-Transport
