### ISSUE TITLE
Multiple POI files

### ISSUE THREAD

**Issue by stvno** [WorldBank-Transport/rra-frontend#51]
Currently there is no way to add more than 1 POI file to a project. A typical usecase would be to calculate the traveltime from villages to various POI-types eg. schools, banks, hospitals. The user would prepare one geojson per POI type and upload all these files and give each a name to display in the results.

**Comment by danielfdsilva** [comment]
This will be implemented in phase 2

**Comment by Holly-Transport** [comment]
If Phase II, then hopefully be the very beginning of Phase II -- as Steven
points out, this is a basic use case.

**Comment by danielfdsilva** [comment]
Implemented
