### ISSUE TITLE
Obsolete results

### ISSUE THREAD

**Issue by danielfdsilva** [WorldBank-Transport/rra-frontend#59]
Once the road network is modified the results become obsolete. This information has to be transmitted to the user.

**Comment by stvno** [comment]
How do you mean obsolete? Isn't the whole point of modifying a road network to compare results between the 'before' and 'after' scenario?

**Comment by olafveerman** [comment]
A more correct term would be `outdated` results. Imagine the following:

1. create a scenario
2. generate results - calculations are shown on the scenario page
3. modify the road network of the scenario through iD

Until new results are generated, the results that are shown on the page (step 2) will not reflect the changes made in step 3. We'd like to clearly communicate that to the users through some sort of message.

**Comment by stvno** [comment]
I see, wouldn't it be a solution to create a new scenario with the modified road network?
This way one can regenerate results on the original scenario and it is clear to which scenario the results belong

**Comment by olafveerman** [comment]
Yes, if you want to compare two different road networks, you'd create two different scenarios. But in the new version of RRA you can also edit the road network through iD. We'd like to allow for users to `edit & generate` more than once on the same scenario.
