### ISSUE TITLE
Running file uploads get canceled by other uploads

### ISSUE THREAD

**Issue by stvno** [WorldBank-Transport/rra-frontend#78]
Uploading a file while another file is still being uploaded cancels the upload on the other file. 
This happens for instance when uploading a large road network (few hundred MB) and you immediately try to upload for instance a small profile file.

Either make sure multiple uploads can run parallel, queue them or disallow uploading hen there is still a file going up.

**Comment by danielfdsilva** [comment]
@stvno Thanks for flagging this. Since the file upload part will be improved on phase 2, we'll fix the problem when doing that, so we avoid writing code that will be discarded.

**Comment by danielfdsilva** [comment]
Fixed with the new upload system
