### ISSUE TITLE
Style form errors

### ISSUE THREAD

**Issue by olafveerman** [WorldBank-Transport/rra-frontend#80]
Form errors blend in with the rest of the text. We should style them slightly.

![image](https://cloud.githubusercontent.com/assets/751330/25304807/b2b42e96-273c-11e7-8dcc-497e3d18cb27.png)

cc @ricardomestre

**Comment by ricardomestre** [comment]
Fixed via alert system.

![screen shot 2017-05-03 at 11 06 56](https://cloud.githubusercontent.com/assets/1016701/25656381/a9f82a70-2ff0-11e7-8aae-e319e22a3213.png)
